services:
  kraken-5.3.0-cu121:
    image: kraken-5.3.0-cu121:local
    build:
        dockerfile: kraken-cuda.Dockerfile
        platform: 
            # the created image installs WSL specific CUDA drivers, so only Windows/WSL is supported
            - "windows/amd64" 
    entrypoint: sh -c "while [ -e / ] ; do echo . ; sleep 1h ; done"
    volumes:
      - "../ocr4all-data:/var/kraken/data"
      - "../ocr4all-models:/var/kraken/models"
    restart: "no"
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: all
